alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

input_datetime:
  downstairs_last_motion:
    name: Downstairs last motion
    has_date: true
    has_time: true
  hall_last_motion:
    name: Hall last motion
    has_date: true
    has_time: true
  last_door_closed:
    name: Last door closed
    has_date: true
    has_time: true

sensor:
  - platform: template
    sensors:
      someone_downstairs:
        friendly_name: "Someone Downstairs"
        value_template: >-
          {% set downstairs_last_motion = state_attr('input_datetime.downstairs_last_motion','timestamp') %}
          {% set last_door_closed = state_attr('input_datetime.last_door_closed','timestamp') %}
          {% set hall_last_motion = state_attr('input_datetime.hall_last_motion','timestamp') %}
          {% if downstairs_last_motion > last_door_closed and downstairs_last_motion > hall_last_motion %}
            Yes
          {% else %}
            Maybe
          {% endif %}

automation:
  - alias: 'Trigger alarm while armed away'
    trigger:
      - platform: state
        entity_id: group.door_sensors
        to: 'on'
      - platform: state
        entity_id: group.window_sensors
        to: 'on'
      - platform: state
        entity_id: group.upstairs_motion_sensors
        to: 'on'
      - platform: state
        entity_id: group.downstairs_motion_sensors
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home_alarm
      - service: notify.html5_blake_phone
        data_template:
          message: "{{ trigger.to_state.attributes.friendly_name }} has triggered the alarm!"
    
  - alias: Garage doors set off alarm
    trigger:
      - platform: state
        entity_id: cover.ali_s_garage_door
        to: 'open'
        for:
          minutes: 2
      - platform: state
        entity_id: cover.blake_s_garage_door
        to: 'open'
        for:
          minutes: 2
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home_alarm
      - service: notify.html5_blake_phone
        data_template:
          message: "{{ trigger.to_state.attributes.friendly_name }} has triggered the alarm!"

  - alias: Send notification when alarm triggered
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: 'triggered'
    action:
      service: notify.html5_blake_phone
      data:
        message: "The alarm is going off!"

  - alias: Disarm when the keypad unlocks the door
    trigger:
      - platform: state
        entity_id: sensor.back_door_last_action
        to: 'Keypad Unlock'
      - platform: state
        entity_id: sensor.front_door_last_action
        to: 'Keypad Unlock'
    action:
      - service: notify.html5_blake_phone
        data_template:
          message: "{{ trigger.to_state.attributes.lock_status }}"
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home_alarm
          code: !secret alarm_code

  - alias: Notify me when the keypad locks the door
    trigger:
      - platform: state
        entity_id: sensor.back_door_last_action
        to: 'Keypad Lock'
      - platform: state
        entity_id: sensor.front_door_last_action
        to: 'Keypad Lock'
    action:
      - service: notify.html5_blake_phone
        data_template:
          message: "{{ trigger.to_state.attributes.lock_status }}"
      - condition: state
        entity_id: group.people
        state: 'not_home'
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.home_alarm
          code: !secret alarm_code
          
  # Doesnt work because no state change is triggered for the lock...
  # - alias: Notify me when a bad code is entered
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.back_door_last_action
  #       to: 'Keypad Lock'
  #     - platform: state
  #       entity_id: sensor.front_door_last_action
  #       to: 'Keypad Lock'
  #   action:
  #     - service: notify.html5_blake_phone
  #       data_template:
  #         message: "{{ trigger.to_state.attributes.lock_status }}"

  - alias: Disarm when we arrive
    trigger:
      - platform: state
        entity_id: device_tracker.blake_phone_mqtt
        to: 'home'
      - platform: state
        entity_id: device_tracker.ali_phone_mqtt
        to: 'home'
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home_alarm
          code: !secret alarm_code

  - alias: Arm when we are away
    trigger:
      - platform: state
        entity_id: group.people
        to: 'not_home'
    condition:
      condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    action:
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.home_alarm
          code: !secret alarm_code

  - alias: Lock the doors when we are away
    trigger:
      - platform: state
        entity_id: group.people
        to: 'not_home'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: lock.back_door_lock
            state: 'unlocked'
          - condition: state
            entity_id: lock.front_door_lock
            state: 'unlocked'
    action:
      - service: lock.lock
        entity_id: lock.back_door_lock
      - service: lock.lock
        entity_id: lock.front_door_lock

  - alias: Alert me if the doors cant lock after we leave
    trigger:
      - platform: state
        entity_id: group.people
        to: 'not_home'
        for:
          minutes: 6
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: lock.back_door_lock
            state: 'unlocked'
          - condition: state
            entity_id: lock.front_door_lock
            state: 'unlocked'
    action:
      service: notify.html5_blake_phone
      data:
        message: "Uh oh. I wasn't able to lock the doors automatically."

  - alias: Update the downstairs last motion time
    trigger:
      - platform: state
        entity_id: binary_sensor.pantry_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dining_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_motion
        from: 'off'
        to: 'on'
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.downstairs_last_motion
        data_template:
          time: '{{ (as_timestamp(now()) | timestamp_custom("%H:%M:%S", true)) }}'
          date: '{{ (as_timestamp(now()) | timestamp_custom("%Y-%m-%d", true)) }}'
  
  - alias: Update the last door close
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: binary_sensor.back_door
        from: 'on'
        to: 'off'
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.last_door_closed
        data_template:
          time: '{{ (as_timestamp(now()) | timestamp_custom("%H:%M:%S", true)) }}'
          date: '{{ (as_timestamp(now()) | timestamp_custom("%Y-%m-%d", true)) }}'

  - alias: Update the hall last motion
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.boys_doors_motion
        from: 'off'
        to: 'on'
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.hall_last_motion
        data_template:
          time: '{{ (as_timestamp(now()) | timestamp_custom("%H:%M:%S", true)) }}'
          date: '{{ (as_timestamp(now()) | timestamp_custom("%Y-%m-%d", true)) }}'
