input_boolean:
  baby_monitor:
    name: Baby Monitor Mode
    initial: off
    icon: mdi:baby-buggy

automation:
  - alias: 'Motion detected in the house'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001215452
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001d66c8d
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001b15d45
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001b15d41
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001e1845a
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001ad44f0
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001a2ba1f
        to: 'on'
      - platform: state
        entity_id: binary_sensor.back_door
        to: 'on'
      - platform: state
        entity_id: binary_sensor.front_door
        to: 'on'
      - platform: state
        entity_id: binary_sensor.boys_doors_motion
        to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.baby_monitor
      state: 'on'
    action:
      - service: notify.html5_blake_phone
        data_template:
          message: "{{ trigger.to_state.attributes.friendly_name }} has detected motion!"
      - service: notify.html5_ali_phone
        data_template:
          message: "{{ trigger.to_state.attributes.friendly_name }} has detected motion!"