scene:
  - name: Lockup
    entities:
      lock.back_door_lock: locked
      lock.front_door_lock: locked
      cover.blakes_garage_door: closed
      cover.alis_garage_door: closed

sensor:
  platform: template
  sensors:
    locked_up:
      friendly_name: "Doors and Garage"
      value_template: >-
        {% if is_state('lock.back_door_lock', 'unlocked') or 
              is_state('lock.front_door_lock','unlocked') or
              is_state('cover.blakes_garage_door', 'open') or
              is_state('cover.alis_garage_door', 'open')  %}
          Not Secured
        {% else %}
          Secured
        {% endif %}

automation:
  - alias: Turn on the master status light red if not locked up after 9PM
    trigger:
      - platform: time
        at: '21:00'
      - platform: state
        entity_id: sensor.locked_up
        to: 'Not Secured'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.locked_up
          state: 'Not Secured'
        - condition: time
          after: '20:59'
    action:
      service: light.turn_on
      data:
        entity_id: light.gateway_light_286c07fa2266
        color_name: red
        brightness_pct: 100
  - alias: Turn off the master status light red if locked up after 9PM
    trigger:
      - platform: time
        at: '21:00'
      - platform: state
        entity_id: sensor.locked_up
        to: 'Secured'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.locked_up
          state: 'Secured'
    action:
      service: light.turn_off
      data:
        entity_id: light.gateway_light_286c07fa2266
