scene:
  - name: Lockup
    entities:
      lock.back_door_lock: locked
      lock.front_door_lock: locked
      cover.blake_s_garage_door: closed
      cover.ali_s_garage_door: closed

sensor:
  platform: template
  sensors:
    locked_up:
      friendly_name: "Doors and Garage"
      value_template: >-
        {% if is_state('lock.back_door_lock', 'unlocked') or 
              is_state('lock.front_door_lock','unlocked') or
              is_state('cover.blake_s_garage_door', 'open') or
              is_state('cover.ali_s_garage_door', 'open')  %}
          Not Secured
        {% else %}
          Secured
        {% endif %}

