version: "3"
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    volumes:
      - /srv/blakeshome/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
    ports:
      - "1883:1883"
      - "9001:9001"
  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - "127.0.0.1:9000:9000"
  nodered:
    container_name: nodered
    image: nodered/node-red-docker:latest
    volumes:
      - nodered_data:/data
    network_mode: host
    environment:
      TZ: "America/Chicago"
  unifi:
    container_name: unifi
    image: jacobalberty/unifi
    volumes:
      - unifi:/unifi
    network_mode: host
    environment:
      TZ: "America/Chicago"
      RUNAS_UID0: "false"
  googletracker:
    container_name: google_tracker
    restart: unless-stopped
    build:
      context: googletracker
    environment:
      TZ: "America/Chicago"
      EMAIL: blakeshome.tracker@gmail.com
      PASSWORD: "${GOOGLETRACKER_PASSWORD}"
      POLL_INTERVAL: 300
      MQTT_SERVER: mqtt.blakeshome.com
      HOME_LATITUDE: "${GOOGLETRACKER_HOME_LATITUDE}"
      HOME_LONGITUDE: "${GOOGLETRACKER_HOME_LONGITUDE}"
    network_mode: host
  homeassistant:
    container_name: hass
    image: homeassistant/home-assistant:0.63.3
    volumes:
      - /srv/blakeshome/home-assistant:/config
    network_mode: host
    environment:
      TZ: "America/Chicago"
  pihole:
    container_name: pihole
    restart: unless-stopped
    build:
      context: pihole
    environment:
      TZ: "America/Chicago"
      WEBPASSWORD: "${DOCKER_PIHOLE_PW}"
      ServerIP: 192.168.2.2
      VIRTUAL_HOST: pihole.blakeshome.com
      INTERFACE: enp3s0
      DNSMASQ_LISTENING: local
      DHCP_ACTIVE: "true"
      DHCP_START: 192.168.2.30
      DHCP_END: 192.168.2.251
      DHCP_ROUTER: 192.168.2.1
      DHCP_LEASETIME: 1
      PIHOLE_DOMAIN: local
    volumes:
      - pihole:/etc/pihole
      - /srv/blakeshome/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /srv/blakeshome/pihole/mqttpub.sh:/opt/mqttpub.sh:ro
    cap_add:
      - NET_ADMIN
    network_mode: host
  oauth2_proxy:
    container_name: oauth2_proxy
    restart: unless-stopped
    image: blakeblackshear/oauth2_proxy
    volumes:
      - /srv/blakeshome/oauth2_proxy:/etc/oauth2_proxy:ro
    network_mode: host
    environment:
      OAUTH2_PROXY_CLIENT_ID: 114257218611-r0nucuv66g6n0h7dcsvnhqprgr6rq1jg.apps.googleusercontent.com
      OAUTH2_PROXY_CLIENT_SECRET: "${OAUTH2_PROXY_CLIENT_SECRET}"
      OAUTH2_PROXY_COOKIE_SECRET: "${OAUTH2_PROXY_COOKIE_SECRET}"
      OAUTH2_PROXY_COOKIE_DOMAIN: blakeshome.com
    command: -config=/etc/oauth2_proxy/oauth2_proxy.cfg
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: rrusakov/nginx-naxsi-nginscript:latest
    volumes:
      - /srv/blakeshome/nginx/conf.d:/etc/nginx/conf.d:ro
      - /srv/blakeshome/nginx/html:/etc/nginx/html:ro
      - /srv/blakeshome/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/blakeshome/nginx/whitelist.rules:/etc/nginx/whitelist.rules:ro
      - ssl_certs:/etc/ssl/private:ro
    network_mode: host
  lets_encrypt:
    container_name: acme.sh
    restart: unless-stopped
    image: neilpang/acme.sh
    command: daemon
    volumes:
      - ssl_certs:/acme.sh
    network_mode: host
    environment:
      CF_Email: blakeb@blakeshome.com
      CF_Key: "${DOCKER_CF_KEY}"

volumes:
  mosquitto_data:
  nodered_data:
  unifi:
  pihole:
  ssl_certs:
  portainer: