automation:
  - alias: Prompt for cooling off the media room if its hot and we are in town
    trigger:
      platform: time
      at: '19:00'
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: proximity.blake_home
          below: '32000'
        - condition: numeric_state
          entity_id: sensor.media_temperature
          above: '74'
        - condition: state
          entity_id: climate.media
          state: 'off'
    action:
      service: notify.blake_telegram
      #target: ['specific device to notify']
      data:
        message: "Should I cool down the media room?"
        data:
          inline_keyboard:
            - 'Yes:/cool_media'

  - alias: Cool media action clicked
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/cool_media'
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.media_temperature
          above: '74'
        - condition: state
          entity_id: climate.media
          state: 'off'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.media
          operation_mode: 'cool'
      - service: climate.set_temperature
        data_template:
          temperature: 71
          entity_id:
            - climate.media

  - alias: Turn off media thermostat at 9:30pm
    trigger:
      platform: time
      at: '21:30'
    action:
      service: climate.set_operation_mode
      data:
        entity_id: climate.media
        operation_mode: 'off'
    