binary_sensor:
  - platform: "mqtt"
    name: Living Room Motion
    state_topic: "zigbee/0x00158d0001d54b06"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"
    json_attributes: 
      - "battery"
      - "voltage"