media_player:
  - platform: samsungtv
    host: 192.168.2.121
    port: 8001
    name: Downstairs TV
    mac: e4:7d:bd:47:84:6a

automation:
  - alias: Turn off the tv when the harmony turns off
    trigger: 
      - platform: state
        entity_id: remote.living_room
        from: 'on'
        to: 'off'
    action:
      - service: media_player.turn_off
        entity_id:
          - media_player.downstairs_tv
  - alias: Turn off the tv when switching to Listen to Music
    trigger: 
      - platform: template
        value_template: '{{ is_state_attr("remote.living_room", "current_activity", "Listen to Music") }}'
    action:
      - service: media_player.turn_off
        entity_id:
          - media_player.downstairs_tv
  - alias: Turn on the tv when switching to Play a Game
    trigger: 
      - platform: template
        value_template: '{{ is_state_attr("remote.living_room", "current_activity", "Play a Game") }}'
    action:
      - service: media_player.turn_on
        entity_id:
          - media_player.downstairs_tv