switch:
  - platform: rest
    name: Downstairs TV
    resource: http://192.168.2.224:5000/device/0/power
    body_on: '{"state":"on"}'
    body_off: '{"state":"off"}'
    is_on_template: '{{ value_json.state == "starting" or value_json.state == "on" }}'
  - platform: rest
    name: Downstairs Shield
    resource: http://192.168.2.224:5000/device/4/power
    body_on: '{"state":"on"}'
    body_off: '{"state":"off"}'
    is_on_template: '{{ value_json.state == "starting" or value_json.state == "on" }}'

automation:
  - alias: Turn off the tv when the harmony turns off
    trigger: 
      - platform: state
        entity_id: remote.living_room
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id:
          - switch.downstairs_tv
  - alias: Turn off the tv when switching to Listen to Music
    trigger: 
      - platform: template
        value_template: '{{ is_state_attr("remote.living_room", "current_activity", "Listen to Music") }}'
    action:
      - service: switch.turn_off
        entity_id:
          - switch.downstairs_tv
  - alias: Turn on the tv when switching to Play a Game
    trigger: 
      - platform: template
        value_template: '{{ is_state_attr("remote.living_room", "current_activity", "Play a Game") }}'
    action:
      - service: switch.turn_on
        entity_id:
          - switch.downstairs_tv
  - alias: Turn off the harmony remote when the shield goes to sleep if in Play a Game mode
    trigger: 
      - platform: state
        entity_id: switch.downstairs_shield
        from: 'on'
        to: 'off'
    condition:
      condition: template
      value_template: '{{ is_state_attr("remote.living_room", "current_activity", "Play a Game") }}'
    action:
      - service: remote.turn_off
        entity_id:
          - remote.living_room