automation:
  - alias: Open blake's garage door when button turns on
    trigger:
      platform: mqtt
      topic: homeassistant_hub/events
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.entity_id=='zwave.back_panel' }}"
      - condition: template
        value_template: "{{ trigger.payload_json.scene_id==4 }}"
    action:
      - service: cover.open_cover
        entity_id:
          - cover.blakes_garage_door
  - alias: Close blake's garage door when the button turns off
    trigger:
      platform: state
      entity_id: switch.back_panel_led_4
      from: 'on'
      to: 'off'
    action:
      - service: cover.close_cover
        entity_id:
          - cover.blakes_garage_door
  # - alias: Turn off button when blake's garage door is closed
  #   trigger:
  #     - platform: state
  #       entity_id: cover.blakes_garage_door
  #       from: 'open'
  #       to: 'closed'
  #   action:
  #     - service: switch.turn_off
  #       entity_id:
  #         - switch.back_panel_led_4
  # - alias: Turn on button when blake's garage door is opened
  #   trigger:
  #     - platform: state
  #       entity_id: cover.blakes_garage_door
  #       from: 'closed'
  #       to: 'open'
  #   action:
  #     - service: switch.turn_on
  #       entity_id:
  #         - switch.back_panel_led_4

  
  - alias: Open ali's garage door when button turns on
    trigger:
      platform: mqtt
      topic: homeassistant_hub/events
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.entity_id=='zwave.back_panel' }}"
      - condition: template
        value_template: "{{ trigger.payload_json.scene_id==5 }}"
    action:
      - service: cover.open_cover
        entity_id:
          - cover.alis_garage_door
  - alias: Close ali's garage door when the button turns off
    trigger:
      platform: state
      entity_id: switch.back_panel_led_5
      from: 'on'
      to: 'off'
    action:
      - service: cover.close_cover
        entity_id:
          - cover.alis_garage_door
  # - alias: Turn off button when ali's garage door is closed
  #   trigger:
  #     - platform: state
  #       entity_id: cover.alis_garage_door
  #       from: 'open'
  #       to: 'closed'
  #   action:
  #     - service: switch.turn_off
  #       entity_id:
  #         - switch.back_panel_led_5
  # - alias: Turn on button when ali's garage door is opened
  #   trigger:
  #     - platform: state
  #       entity_id: cover.alis_garage_door
  #       from: 'closed'
  #       to: 'open'
  #   action:
  #     - service: switch.turn_on
  #       entity_id:
  #         - switch.back_panel_led_5