timer:
  outside_lights_after_dark:
    duration: '00:05:00'

automation:
  - alias: Turn on the outside lights if the garage opens at night
    trigger:
      - platform: state
        entity_id: cover.ali_s_garage_door
        from: 'closed'
        to: 'open'
      - platform: state
        entity_id: cover.blake_s_garage_door
        from: 'closed'
        to: 'open'
    condition:
      condition: sun
      after: sunset
    action:
      - service: scene.turn_on
        entity_id: scene.backyard_night_active
      - service: timer.start
        entity_id: timer.outside_lights_after_dark

  - alias: Turn off the outside lights after the timer expires at night
    trigger: 
      platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.outside_lights_after_dark
    action:
      - wait_template: "{{ states.sensor.backyard_person.state == 'off' }}"
        timeout: '00:10:00'
        continue_on_timeout: 'false'
      - service: scene.turn_on
        entity_id: scene.backyard_night_normal
  
  - alias: Turn off the outside lights if the door locks when the timer is running
    trigger:
      - platform: mqtt
        topic: "homeassistant_hub/lock/back_door/state"
    condition:
      - condition: state
        entity_id: timer.outside_lights_after_dark
        state: 'active'
      - condition: template
        value_template: "{{ 'Manual Lock' == trigger.payload_json.notification }}"
    action:
      - service: timer.finish
        entity_id: timer.outside_lights_after_dark
