automation:
  - alias: Notify if the garage doors are open
    trigger:
      - platform: state
        entity_id: group.people
        to: 'not_home'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: group.garage_doors
        state: open
    action:
      - service: notify.blake_telegram
        data:
          message: "The garage is open, but nobody is home!"
          data:
            inline_keyboard:
              - 'Close Garage:/close_garage'

  - alias: Close garage from notification
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/close_garage'
    action:
      - service: cover.close_cover
        entity_id:
          - cover.blake_s_garage_door
          - cover.ali_s_garage_door