sensor:
  - platform: mqtt
    name: "Water Heater Energy"
    state_topic: "tele/sonoff-0AED33/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Water Heater Power"
    state_topic: "tele/sonoff-0AED33/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Water Heater Voltage"
    state_topic: "tele/sonoff-0AED33/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Water Heater Current"
    state_topic: "tele/sonoff-0AED33/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"

  - platform: mqtt
    name: "Dehumidifier Energy"
    state_topic: "tele/sonoff-3491/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Dehumidifier Power"
    state_topic: "tele/sonoff-3491/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Dehumidifier Voltage"
    state_topic: "tele/sonoff-3491/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Dehumidifier Current"
    state_topic: "tele/sonoff-3491/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"