sensor:
  - platform: mqtt
    name: "Energy-0AED33"
    state_topic: "tele/sonoff-0AED33/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Power-0AED33"
    state_topic: "tele/sonoff-0AED33/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Voltage-0AED33"
    state_topic: "tele/sonoff-0AED33/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Current-0AED33"
    state_topic: "tele/sonoff-0AED33/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"

  - platform: mqtt
    name: "Energy-3491"
    state_topic: "tele/sonoff-3491/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Power-3491"
    state_topic: "tele/sonoff-3491/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Voltage-3491"
    state_topic: "tele/sonoff-3491/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Current-3491"
    state_topic: "tele/sonoff-3491/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"