sensor:
  - platform: template
    sensors:
      crawl_space_temperature_battery:
        friendly_name: "Crawl Space Temperature Battery"
        unit_of_measurement: '%'
        value_template: "{{ states.sensor.temperature_158d0001c163e1.attributes.battery_level|default(-1)|int }}"
        icon_template: '{% if states.sensor.temperature_158d0001c163e1.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.sensor.temperature_158d0001c163e1.attributes.battery_level < 10 %}
                           battery-outline
                        {% else %}
                          mdi:battery-{{(states.sensor.temperature_158d0001c163e1.attributes.battery_level/10)|int*10}}
                        {% endif %}'
        