sensor:
  - platform: template
    sensors:
      pantry_motion_battery:
        friendly_name: "Pantry Motion Battery"
        unit_of_measurement: '%'
        value_template: "{{ states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level|default(-1)|int }}"
        icon_template: '{% if states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.binary_sensor.motion_sensor_158d0001a2ba1f.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'
        entity_id: binary_sensor.motion_sensor_158d0001a2ba1f