homeassistant:
  customize:
    light.gateway_light_286c07fa2266:
      friendly_name: Status Light

    sensor.illumination_286c07fa2266:
      friendly_name: Ambient Light

    sensor.temperature_158d0001c163e1:
      friendly_name: Crawl Space Temperature

    sensor.humidity_158d0001c163e1:
      friendly_name: Crawl Space Humidity