sensor:
  - platform: mqtt
    name: Front Door Lock Battery
    state_topic: "zway/ZWayVDev_zway_50-0-128/status"
    unit_of_measurement: '%'
  - platform: mqtt
    name: Back Door Lock Battery
    state_topic: "zway/ZWayVDev_zway_57-0-128/status"
    unit_of_measurement: '%'
  - platform: mqtt
    name: Front Door Sensor Battery
    state_topic: "zway/ZWayVDev_zway_45-0-128/status"
    unit_of_measurement: '%'
  - platform: mqtt
    name: Back Door Sensor Battery
    state_topic: "zway/ZWayVDev_zway_46-0-128/status"
    unit_of_measurement: '%'