light:
  - platform: group
    name:  Master Lamps
    entities:
      - light.master_blake_lamp
      - light.master_ali_lamp

automation:
  - alias: Toggle Blake lamp
    trigger:
      platform: mqtt
      topic: 'zigbee/0x00158d00022449ea'
    condition:
      condition: template
      value_template: "{{ 'single' == trigger.payload_json.click }}"
    action:
      service: light.toggle
      entity_id: light.master_blake_lamp

  - alias: Toggle Ali lamp
    trigger:
      platform: mqtt
      topic: 'zigbee/0x00158d00019de5ec'
    condition:
      condition: template
      value_template: "{{ 'single' == trigger.payload_json.click }}"
    action:
      service: light.toggle
      entity_id: light.master_ali_lamp

  - alias: Toggle both lamps
    trigger:
      - platform: mqtt
        topic: 'zigbee/0x00158d00022449ea'
      - platform: mqtt
        topic: 'zigbee/0x00158d00019de5ec'
    condition:
      condition: template
      value_template: "{{ 'double' == trigger.payload_json.click }}"
    action:
      service: light.toggle
      entity_id: light.master_lamps

  - alias: Turn off bathroom lights with triple tap
    trigger:
      - platform: mqtt
        topic: 'zigbee/0x00158d00022449ea'
      - platform: mqtt
        topic: 'zigbee/0x00158d00019de5ec'
    condition:
      condition: template
      value_template: "{{ 'triple' == trigger.payload_json.click }}"
    action:
      service: light.turn_off
      entity_id: light.all_master_bath_lights