binary_sensor:
  - platform: "mqtt"
    name: Master Closet Motion
    state_topic: "zigbee/0x00158d0001b15d45"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"
    json_attributes: 
      - "battery"
      - "voltage"

timer:
  master_closet_lights:
    duration: '00:02:00'

automation:
  - alias: Turn on master closet lights with motion
    trigger:
      platform: state
      entity_id: binary_sensor.master_closet_motion
      to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.master_closet_lights
      - service: light.turn_on
        entity_id: light.master_closet_lights
        data_template:
          brightness: >
            {% if now().hour < 7 or now().hour > 22 %}60
            {% else %}250
            {% endif %}
  - alias: Start master closet lights timer with no motion
    trigger:
      platform: state
      entity_id: binary_sensor.master_closet_motion
      to: 'off'
    action:
      service: timer.start
      entity_id: timer.master_closet_lights

  - alias: Turn off the master closet lights after the timer expires
    trigger: 
      platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.master_closet_lights
    action:
      service: light.turn_off
      entity_id: light.master_closet_lights