light:
  - platform: group
    name:  All Master Bath Lights
    entities:
      - light.master_bath_lights
      - light.master_closet_lights
      - light.master_shower_light

sensor:
  - platform: "mqtt"
    name: Master Bath Temperature
    state_topic: "zigbee/0x00158d0001c164af"
    availability_topic: "zigbee/bridge/state"
    unit_of_measurement: "°F"
    icon: "mdi:thermometer"
    value_template: "{{ ((float(value_json.temperature) * 9 / 5 ) + 32) | round(1) }}"
    json_attributes: 
      - "battery"
      - "voltage"
      - "linkquality"
  - platform: "mqtt"
    name: Master Bath Humidity
    state_topic: "zigbee/0x00158d0001c164af"
    availability_topic: "zigbee/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    value_template: "{{ value_json.humidity }}"
    json_attributes: 
      - "battery"
      - "voltage"
      - "linkquality"