binary_sensor:
  - platform: "mqtt"
    name: Blake Bedside Motion
    state_topic: "zigbee/0x00158d0001b15d41"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"
  - platform: "mqtt"
    name: Ali Bedside Motion
    state_topic: "zigbee/0x00158d0001e1845a"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"