- alias: Toggle Blake lamp
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00019de5ec
      click_type: single
  action:
    service: light.toggle
    entity_id: light.master_blake_lamp

- alias: Toggle Master lamps
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00019de5ec
        click_type: double
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00016d7770
        click_type: double
  action:
    service: light.toggle
    entity_id: group.master_lamps

- alias: Toggle Ali lamp
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016d7770
      click_type: single
  action:
    service: light.toggle
    entity_id: light.master_ali_lamp

- alias: Turn on Porch Light at Sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.porch_lights
    data:
      brightness_pct: 40

- alias: Turn off Porch Light at Sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.porch_lights

- alias: Turn on Living Room Lamps before it gets dark
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    - service: light.turn_on
      entity_id: light.living_room_front_lamp
      data:
        brightness_pct: 100
    - service: light.turn_on
      entity_id: light.living_room_back_lamp
      data:
        brightness_pct: 100

- alias: Turn off back living room lamp at 11 pm
  trigger:
    platform: time
    at: '23:00'
  action:
    service: light.turn_off
    entity_id: light.living_room_back_lamp

- alias: Turn off living room lamps one hour after sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "01:00:00"
  action:
    - service: light.turn_off
      entity_id: light.living_room_front_lamp
    - service: light.turn_off
      entity_id: light.living_room_back_lamp

## Hall Lamps
- alias: Turn on hall lamps one hour after sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "01:00:00"
  action:
    service: light.turn_on
    entity_id: 
      - light.hall_right_lamp
      - light.hall_left_lamp
    data:
        brightness_pct: 100

- alias: Dim hall lamps one hour before sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: light.turn_on
    entity_id: 
      - light.hall_right_lamp
      - light.hall_left_lamp
    data:
        brightness_pct: 50

- alias: Turn off hall lamps at 10
  trigger:
    platform: time
    at: '22:00'
  action:
    service: light.turn_off
    entity_id: 
      - light.hall_right_lamp
      - light.hall_left_lamp

- alias: Turn on hall lamps at night with motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001d66c8d
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: time
        after: '22:00:00'
      - condition: sun
        before: sunrise
        before_offset: "01:00:00"
  action:
    service: light.turn_on
    entity_id: 
      - light.hall_right_lamp
    data:
        brightness_pct: 3

- alias: Turn off hall lamps at night with no motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001d66c8d
    to: 'off'
  condition:
    condition: or
    conditions:
      - condition: time
        after: '22:00:00'
      - condition: sun
        before: sunrise
        before_offset: "01:00:00"
  action:
    - service: light.turn_off
      entity_id: 
        - light.hall_right_lamp
        - light.hall_left_lamp

## Pantry Light
- alias: Turn on pantry light with motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001a2ba1f
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.pantry_light

- alias: Turn off pantry light with no motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001a2ba1f
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.pantry_light

## Laundry Room
- alias: Turn on laundry light with motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001215452
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.laundry_room_light

- alias: Turn off laundry light with no motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001215452
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.laundry_room_light

## Play Room
- alias: Turn on playroom light with motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001ad43f0
    to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.playroom_lights
    - service: light.turn_on
      entity_id: light.playroom_light

- alias: Start playroom light timer with no motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001ad43f0
    to: 'off'
  action:
    service: timer.start
    entity_id: timer.playroom_lights

- alias: Turn off the playroom lights after the timer expires
  trigger: 
    platform: event
    event_type: timer.finished
    event_data: 
      entity_id: timer.playroom_lights
  action:
    service: light.turn_off
    entity_id: light.playroom_light

## Garage

- alias: Open the garage door at 8:45 MWF if Ali is home
  trigger:
    platform: time
    at: '08:45'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.android891a4643e48d8ac4
        state: home
      - condition: time
        weekday:
          - mon
          - wed
          - fri
  action:
    service: cover.open_cover
    entity_id: cover.alis_garage_door

- alias: Turn on the driveway lights if the garage opens at night
  trigger:
    - platform: state
      entity_id: cover.alis_garage_door
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id: cover.blakes_garage_door
      from: 'closed'
      to: 'open'
  condition:
    condition: sun
    after: sunset
  action:
    - service: light.turn_on
      entity_id:
        - light.deck_string_lights
        - light.driveway_lights
        - light.deck_recessed_lights
      data:
        brightness_pct: 75
    - service: timer.start
      entity_id: timer.outside_lights_after_dark

- alias: Turn off the outside lights after the timer expires at night
  trigger: 
    platform: event
    event_type: timer.finished
    event_data: 
      entity_id: timer.outside_lights_after_dark
  action:
    - service: light.turn_off
      entity_id:
        - light.deck_string_lights
        - light.driveway_lights
        - light.deck_recessed_lights
  