homeassistant:
  # Name of the location where Home Assistant is running
  name: Blakeshome
  # Location required to calculate the time the sun rises and sets
  latitude: !secret blakeshome_latitude
  longitude: !secret blakeshome_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 229
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  extra_html_url: /local/custom_ui/oauth.html
  extra_html_url_es5: /local/custom_ui/oauth.html

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://hass.blakeshome.com

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:
  ignore:
    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

recorder:
  db_url: !secret postgres_url


# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# MQTT
mqtt:
  broker: mqtt.blakeshome.com
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    retain: true
  # discovery: true
  # discovery_prefix: homeassistant

map:

emulated_hue:

vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.36
    token: !secret xiaomi_vacuum_token

cover:
  - platform: mqtt
    name: "Blake's Garage Door"
    command_topic: "taproot/garage/blake/set"
    state_topic: "taproot/garage/blake/status"
  - platform: mqtt
    name: "Ali's Garage Door"
    command_topic: "taproot/garage/ali/set"
    state_topic: "taproot/garage/ali/status"

ecobee:
  api_key: !secret ecobee_api_key

group: !include groups.yaml
script: !include scripts.yaml


twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret google_messaging_server_key
    gcm_sender_id: !secret google_messaging_sender_id
  - name: blakeshome_call
    platform: twilio_call
    from_number: !secret twilio_phone_number
  - name: blakeshome_sms
    platform: twilio_sms
    from_number: !secret twilio_phone_number