homeassistant:
  # Name of the location where Home Assistant is running
  name: Blakeshome
  # Location required to calculate the time the sun rises and sets
  latitude: !secret blakeshome_latitude
  longitude: !secret blakeshome_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 229
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  extra_html_url: /local/custom_ui/oauth.html
  extra_html_url_es5: /local/custom_ui/oauth.html

# Enables configuration UI
config:

http:
  base_url: https://hass.blakeshome.com
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:
  ignore:
    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
      - automation.update_battery_status_group_members
      - automation.battery_notification
      - automation.battery_notification_clear
      - automation.battery_sensor_from_attributes
      - automation.clear_mqtt_topic
      - automation.filter_out_blake_s_location_updates_that_are_old_and_republish
      - automation.filter_out_ali_s_location_updates_that_are_old_and_republish
      - automation.update_blake_last_seen_from_unifi
      - automation.update_ali_last_seen_from_unifi

recorder:
  db_url: !secret postgres_url

system_health:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate

# MQTT
mqtt:
  broker: mqtt.blakeshome.com
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    retain: true
  discovery: true
  discovery_prefix: hass

map:

emulated_hue:

vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.36
    token: !secret xiaomi_vacuum_token

cover:
  - platform: mqtt
    name: "Blake's Garage Door"
    command_topic: "taproot/garage/blake/set"
    state_topic: "taproot/garage/blake/status"
  - platform: mqtt
    name: "Ali's Garage Door"
    command_topic: "taproot/garage/ali/set"
    state_topic: "taproot/garage/ali/status"

ecobee:
  api_key: !secret ecobee_api_key

group: !include groups.yaml
script: !include scripts.yaml

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
  - platform: darksky
    api_key: !secret dark_sky_secret
    forecast:
      - 1
    monitored_conditions:
      - summary
      - temperature
      - apparent_temperature
      - humidity
      - precip_probability
      - precip_intensity
      - precip_type
      - wind_speed
      - wind_bearing
      - pressure
      - icon

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_api_key
    trusted_networks:
      - 149.154.160.0/20
      - 91.108.4.0/22
    allowed_chat_ids:
      - 707447684

notify:  
  - name: blake_telegram
    platform: telegram
    chat_id: 707447684
  - name: html5
    platform: html5
    gcm_api_key: !secret google_messaging_server_key
    gcm_sender_id: !secret google_messaging_sender_id
  - name: blakeshome_call
    platform: twilio_call
    from_number: !secret twilio_phone_number
  - name: blakeshome_sms
    platform: twilio_sms
    from_number: !secret twilio_phone_number

panel_custom:
  - name: frigate
    sidebar_title: Frigate
    sidebar_icon: mdi:cctv
    # This is the url that will load the panel
    url_path: frigate
    # Location where the panel is hosted during development
    js_url: https://cameras.blakeshome.com/static/js/main.fcde51b5.js
    # We want to load in an iframe to work around limitations in React
    embed_iframe: true
    # This will be available as prop `panel.config`.
    config:
      api_url: https://cameras.blakeshome.com
      camera_streams: back