homeassistant:
  # Name of the location where Home Assistant is running
  name: Blakeshome
  # Location required to calculate the time the sun rises and sets
  latitude: !secret blakeshome_latitude
  longitude: !secret blakeshome_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 229
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  extra_html_url: /local/custom_ui/oauth.html
  extra_html_url_es5: /local/custom_ui/oauth.html

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://hass.blakeshome.com

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:



# Text to speech
tts:
  - platform: google

# MQTT
mqtt:
  broker: mqtt.blakeshome.com
  discovery: true
  discovery_prefix: homeassistant

light:
  - platform: mqtt
    name: Foyer Back Light
    state_topic: zwave/downstairs/ZWayVDev_zway_20-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_20-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_20-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_20-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Foyer Front Light
    state_topic: zwave/downstairs/ZWayVDev_zway_21-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_21-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_21-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_21-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Living Room Front Lamp
    state_topic: zwave/downstairs/ZWayVDev_zway_30-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_30-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_30-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_30-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Living Room Back Lamp
    state_topic: zwave/downstairs/ZWayVDev_zway_31-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_31-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_31-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_31-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Living Room Chandelier Light
    state_topic: zwave/downstairs/ZWayVDev_zway_12-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_12-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_12-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_12-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Living Room Recessed Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_13-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_13-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_13-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_13-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Butlers Pantry Light
    state_topic: zwave/downstairs/ZWayVDev_zway_2-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_2-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_2-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_2-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Deck Recessed Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_18-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_18-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_18-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_18-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Deck String Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_59-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_59-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_59-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_59-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Dining Room Light
    state_topic: zwave/downstairs/ZWayVDev_zway_6-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_6-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_6-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_6-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Driveway Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_19-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_19-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_19-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_19-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Half Bath Bathroom Light
    state_topic: zwave/downstairs/ZWayVDev_zway_3-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_3-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_3-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_3-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Half Bath Hall Light
    state_topic: zwave/downstairs/ZWayVDev_zway_4-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_4-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_4-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_4-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Hall Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_27-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_27-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_27-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_27-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Hall Stairs Light
    state_topic: zwave/downstairs/ZWayVDev_zway_23-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_23-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_23-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_23-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Kitchen Recessed Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_15-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_15-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_15-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_15-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Kitchen Island Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_16-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_16-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_16-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_16-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Kitchen Breakfast Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_17-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_17-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_17-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_17-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Laundry Room Light
    state_topic: zwave/downstairs/ZWayVDev_zway_26-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_26-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_26-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_26-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Master Blake Lamp
    state_topic: zwave/downstairs/ZWayVDev_zway_32-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_32-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_32-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_32-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Master Ali Lamp
    state_topic: zwave/downstairs/ZWayVDev_zway_33-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_33-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_33-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_33-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Media Stairs Light
    state_topic: zwave/downstairs/ZWayVDev_zway_28-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_28-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_28-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_28-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Pantry Light
    state_topic: zwave/downstairs/ZWayVDev_zway_8-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_8-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_8-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_8-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Playroom Light
    state_topic: zwave/downstairs/ZWayVDev_zway_5-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_5-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_5-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_5-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Porch Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_22-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_22-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_22-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_22-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Hall Right Lamp
    state_topic: zwave/downstairs/ZWayVDev_zway_43-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_43-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_43-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_43-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Hall Left Lamp
    state_topic: zwave/downstairs/ZWayVDev_zway_55-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_55-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_55-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_55-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Master Closet Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_51-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_51-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_51-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_51-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Master Bath Lights
    state_topic: zwave/downstairs/ZWayVDev_zway_52-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_52-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_52-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_52-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'
  - platform: mqtt
    name: Master Shower Light
    state_topic: zwave/downstairs/ZWayVDev_zway_54-0-38/status
    state_value_template: '{{"0" if value == "0" else "255"}}'
    command_topic: zwave/downstairs/ZWayVDev_zway_54-0-38/set
    brightness_state_topic: zwave/downstairs/ZWayVDev_zway_54-0-38/status
    brightness_command_topic: zwave/downstairs/ZWayVDev_zway_54-0-38/set
    brightness_scale: 99
    payload_on: 255
    payload_off: 0
    on_command_type: 'brightness'

device_tracker:
  - platform: mqtt_json
    devices:
      blake_phone_mqtt: location/blake_blackshear
      ali_phone_mqtt: location/ali_blackshear

map:

vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.36
    token: !secret xiaomi_vacuum_token

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 286c07fa2266
      key: !secret xiaomi_key_286c07fa2266

cover:
  - platform: mqtt
    name: "Blake's Garage Door"
    command_topic: "taproot/garage/blake/set"
    state_topic: "taproot/garage/blake/status"
  - platform: mqtt
    name: "Ali's Garage Door"
    command_topic: "taproot/garage/ali/set"
    state_topic: "taproot/garage/ali/status"

ecobee:
  api_key: !secret ecobee_api_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

timer:
  outside_lights_after_dark:
    duration: '00:05:00'
  playroom_lights:
    duration: '00:10:00'

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret google_messaging_server_key
    gcm_sender_id: !secret google_messaging_sender_id