lock:
  - platform: mqtt
    name: Back Door Lock
    state_topic: "homeassistant_hub/lock/back_door/state"
    command_topic: "homeassistant_hub/lock/back_door/set"
    value_template: '{{ value_json.state }}'
    json_attributes:
      - 'notification'
      - 'lock_status'
      - 'battery_level'
  - platform: mqtt
    name: Front Door Lock
    state_topic: "homeassistant_hub/lock/front_door/state"
    command_topic: "homeassistant_hub/lock/front_door/set"
    value_template: '{{ value_json.state }}'
    json_attributes:
      - 'notification'
      - 'lock_status'
      - 'battery_level'

automation:
  - alias: Unlock back door when someone arrives
    trigger:
      - platform: state
        entity_id: device_tracker.blake_phone_mqtt
        to: 'home'
      - platform: state
        entity_id: device_tracker.ali_phone_mqtt
        to: 'home'
    condition:
      condition: time
      after: '08:00:00'
      before: '23:00:00'
    action:
      service: lock.unlock
      entity_id: lock.back_door_lock