camera:
  - name: Backyard Camera
    platform: generic
    still_image_url: https://cameras.blakeshome.com/nvr/back.jpg
  - name: Backyard Last Person
    platform: generic
    still_image_url: http://192.168.2.219:5000/back/best_person.jpg
binary_sensor:
  - name: Backyard Person
    platform: mqtt
    state_topic: "frigate/back/objects"
    value_template: '{{ value_json.person }}'
    device_class: motion
    availability_topic: "frigate/available"

script:
  play_backyard_camera:
    alias: Stream backyard camera
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.living_room
          media_content_id: https://cameras.blakeshome.com/cameras/back.m3u8
          media_content_type: application/vnd.apple.mpegurl

automation:
  - alias: Turn on the outside lights when a person is detected at night
    trigger: 
      platform: state
      entity_id: binary_sensor.backyard_person
      from: 'off'
      to: 'on'
    condition:
      condition: or
      conditions:
        - condition: time
          after: '22:00:00'
        - condition: sun
          before: sunrise
    action:
      - service: scene.turn_on
        entity_id: scene.backyard_night_active
  - alias: Turn off the outside lights when no people are detected at night
    trigger: 
      platform: state
      entity_id: binary_sensor.backyard_person
      from: 'on'
      to: 'off'
      for:
        seconds: 5
    condition:
      condition: or
      conditions:
        - condition: time
          after: '22:00:00'
        - condition: sun
          before: sunrise
    action:
      - service: scene.turn_on
        entity_id: scene.backyard_night_normal
  - alias: Alert me if a person is detected while armed away
    trigger: 
      platform: state
      entity_id: binary_sensor.backyard_person
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    action:
      # - delay: '00:01:00'
      # - condition: state
      #   entity_id: alarm_control_panel.home_alarm
      #   state: armed_away
      - service: notify.blake_telegram
        data_template:
          message: "A person was detected in the backyard."