camera:
  - name: Backyard Camera
    platform: generic
    still_image_url: https://cameras.blakeshome.com/nvr/back.jpg

binary_sensor:
  - name: Backyard Camera Motion
    platform: mqtt
    state_topic: "cameras/back/motion"
    device_class: motion
    availability_topic: "cameras/back/available"

sensor:
  - name: Backyard Person Score
    platform: mqtt
    state_topic: "cameras/back/objects"
    value_template: '{{ value_json.person }}'
    unit_of_measurement: '%'
    availability_topic: "cameras/back/available"

script:
  play_backyard_camera:
    alias: Stream backyard camera
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.living_room
          media_content_id: https://cameras.blakeshome.com/cameras/back.m3u8
          media_content_type: application/vnd.apple.mpegurl

automation:
  - alias: Turn on the outside lights when a person is detected at night
    trigger: 
      platform: numeric_state
      entity_id: sensor.backyard_person_score
      above: 20
    condition:
      condition: or
      conditions:
        - condition: time
          after: '22:00:00'
        - condition: sun
          before: sunrise
    action:
      - service: scene.turn_on
        entity_id: scene.backyard_night_active
  - alias: Turn off the outside lights when no people are detected at night
    trigger: 
      platform: numeric_state
      entity_id: sensor.backyard_person_score
      below: 20
      for:
        seconds: 5
    condition:
      condition: or
      conditions:
        - condition: time
          after: '22:00:00'
        - condition: sun
          before: sunrise
    action:
      - service: scene.turn_on
        entity_id: scene.backyard_night_normal
  - alias: Alert me if a person is detected while armed away
    trigger: 
      platform: numeric_state
      entity_id: sensor.backyard_person_score
      above: 20
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    action:
      # - delay: '00:01:00'
      # - condition: state
      #   entity_id: alarm_control_panel.home_alarm
      #   state: armed_away
      - service: notify.html5_blake_phone
        data_template:
          message: "A person was detected in the backyard."