sensor:
  - platform: "mqtt"
    name: Outside Temperature
    state_topic: "zigbee/0x00158d0001ab4496"
    availability_topic: "zigbee/bridge/state"
    unit_of_measurement: "°F"
    icon: "mdi:temperature-fahrenheit"
    value_template: "{{ ((float(value_json.temperature) * 9 / 5 ) + 32) | round(1) }}"
    json_attributes: 
      - "battery"
      - "voltage"
      - "linkquality"
  - platform: "mqtt"
    name: Outside Humidity
    state_topic: "zigbee/0x00158d0001ab4496"
    availability_topic: "zigbee/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    value_template: "{{ value_json.humidity }}"
    json_attributes: 
      - "battery"
      - "voltage"
      - "linkquality"
  - platform: "mqtt"
    name: Outside Pressure
    state_topic: "zigbee/0x00158d0001ab4496"
    availability_topic: "zigbee/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:gauge"
    value_template: "{{ value_json.pressure }}"
    json_attributes: 
      - "battery"
      - "voltage"
      - "linkquality"