light:
  - platform: mqtt
    schema: json
    name: Dining Room Lights
    state_topic: "homeassistant_hub/light/dining_room/state"
    availability_topic: "homeassistant_hub/status"
    brightness: true
    command_topic: "homeassistant_hub/light/dining_room/set"

binary_sensor:
  - platform: "mqtt"
    name: Dining Room Shutter 1
    state_topic: "zigbee/0x00158d0001b1b1a3"
    availability_topic: "zigbee/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "window"
  - platform: "mqtt"
    name: Dining Room Shutter 2
    state_topic: "zigbee/0x00158d0001b7812e"
    availability_topic: "zigbee/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "window"
  - platform: "mqtt"
    name: Dining Motion
    state_topic: "zigbee/0x00158d0002b95dca"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"

sensor:
  - platform: "mqtt"
    name: Dining Illuminance
    state_topic: "zigbee/0x00158d0002b95dca"
    availability_topic: "zigbee/bridge/state"
    unit_of_measurement: "lx"
    device_class: "illuminance"
    value_template: "{{ value_json.illuminance }}"