automation:
  - alias: Turn on half bath light with motion
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001ad44f0
      to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.half_bath_lights
      - service: light.turn_on
        entity_id: light.half_bath_bathroom_light

  - alias: Start half bath light timer with no motion
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001ad44f0
      to: 'off'
      for:
        minutes: 10
    action:
      service: light.turn_off
      entity_id: light.half_bath_bathroom_light