timer:
  half_bath_lights:
    duration: '00:05:00'

automation:
  - alias: Turn on half bath light with motion
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001ad44f0
      to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.half_bath_lights
      - service: light.turn_on
        entity_id: light.half_bath_bathroom_light

  - alias: Start half bath light timer with no motion
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001ad44f0
      to: 'off'
    action:
      service: timer.start
      entity_id: timer.half_bath_lights

  - alias: Turn off the half bath lights after the timer expires
    trigger: 
      platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.half_bath_lights
    action:
      service: light.turn_off
      entity_id: light.half_bath_bathroom_light