binary_sensor:
  - platform: "mqtt"
    name: Half Bath Motion
    state_topic: "zigbee/0x00158d0001ad44f0"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"

automation:
  - alias: Turn on half bath light with motion
    trigger:
      platform: state
      entity_id: binary_sensor.half_bath_motion
      to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.half_bath_lights
      - service: light.turn_on
        entity_id: light.half_bath_bathroom_light

  - alias: Start half bath light timer with no motion
    trigger:
      platform: state
      entity_id: binary_sensor.half_bath_motion
      to: 'off'
      for:
        minutes: 10
    action:
      service: light.turn_off
      entity_id: light.half_bath_bathroom_light