binary_sensor:
  - platform: "mqtt"
    name: Boys Doors Motion
    state_topic: "zigbee/0x00158d0001b15d3d"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"
  - platform: "mqtt"
    name: Hall Motion
    state_topic: "zigbee/0x00158d0001d66c8d"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"

