binary_sensor:
  - platform: "mqtt"
    name: Playroom Motion
    state_topic: "zigbee/0x00158d0001ad43f0"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"
    json_attributes: 
      - "battery"
      - "voltage"
      - "linkquality"
  - platform: "mqtt"
    name: Play Room Shutter 1
    state_topic: "zigbee/0x00158d0001dcba76"
    availability_topic: "zigbee/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "window"
    json_attributes: 
      - "battery"
      - "voltage"
      - "linkquality"
  - platform: "mqtt"
    name: Play Room Shutter 2
    state_topic: "zigbee/0x00158d0001b780f8"
    availability_topic: "zigbee/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "window"
    json_attributes: 
      - "battery"
      - "voltage"
      - "linkquality"

automation:
  - alias: Turn on playroom light with motion
    trigger:
      platform: state
      entity_id: binary_sensor.playroom_motion
      to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.playroom_light

  - alias: Turn off playroom lights with no motion for 10 min
    trigger:
      platform: state
      entity_id: binary_sensor.playroom_motion
      to: 'off'
      for:
        minutes: 10
    action:
      service: light.turn_off
      entity_id: light.playroom_light