automation:
  - alias: Turn on Outside Lights at Sunset
    trigger:
      platform: sun
      event: sunset
    action:
      - service: light.turn_on
        entity_id: light.porch_lights
        data:
          brightness_pct: 40
      - service: light.turn_on
        entity_id: light.driveway_lights
        data:
          brightness: 50

  - alias: Turn off Outside Lights at Sunrise
    trigger:
      platform: sun
      event: sunrise
    action:
      service: light.turn_off
      entity_id: 
        - light.porch_lights
        - light.driveway_lights