zone:
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 100
    icon: mdi:briefcase

  - name: Gym
    latitude: !secret gym_latitude
    longitude: !secret gym_longitude
    radius: 100
    icon: mdi:dumbbell

  # This will override the default home zone
  - name: Home
    latitude: !secret blakeshome_latitude
    longitude: !secret blakeshome_longitude
    radius: 100
    icon: mdi:home

  - name: Blackshear House
    latitude: !secret blackshear_latitude
    longitude: !secret blackshear_longitude
    radius: 100
    icon: mdi:castle

  - name: Lake
    latitude: !secret lake_latitude
    longitude: !secret lake_longitude
    radius: 5000
    icon: mdi:ferry

proximity:
  ali_home: 
    zone: Home
    devices:
      - device_tracker.ali_phone_mqtt
    tolerance: 50
    unit_of_measurement: m
  blake_home: 
    zone: Home
    devices:
      - device_tracker.blake_phone_mqtt
    tolerance: 50
    unit_of_measurement: m

device_tracker:
  - platform: mqtt_json
    devices:
      blake_phone_mqtt: location/blake_blackshear
      ali_phone_mqtt: location/ali_blackshear
    consider_home: 3600
    new_device_defaults:
      track_new_devices: false
  - platform: unifi
    host: !secret unifi_host
    port: 443
    username: homeassistant
    password: !secret unifi_password
    ssid_filter:
      - 'blakeshome'
    detection_time: 600
    monitored_conditions:
     - signal
     - last_seen
    consider_home: 3600
    new_device_defaults:
      track_new_devices: false
  
sensor:
  - platform: template
    sensors:
      blake_unifi_last_seen:
        friendly_name: Blake Unifi Last Seen
        value_template: "{{ state_attr('device_tracker.blake_phone', 'last_seen') }}"
      ali_unifi_last_seen:
        friendly_name: Ali Unifi Last Seen
        value_template: "{{ state_attr('device_tracker.ali_phone', 'last_seen') }}"

group:
  people:
    name: People
    entities:
      - device_tracker.ali_phone_mqtt
      - device_tracker.blake_phone_mqtt
  devices:
    name: Devices
    entities:
      - device_tracker.blake_phone
      - device_tracker.ali_phone
  guests:
    name: Guests
    entities:
      - device_tracker.faye_phone
      - device_tracker.murray_phone
      - device_tracker.nick_phone
      - device_tracker.brittney_phone
      - device_tracker.bayley_phone
      - device_tracker.beau_phone
      - device_tracker.bentley_phone
      - device_tracker.emma_phone
      - device_tracker.grace_phone
      - device_tracker.grace_watch

input_datetime:
  blake_last_seen:
    name: Blake last seen
    has_date: true
    has_time: true
  ali_last_seen:
    name: Ali last seen
    has_date: true
    has_time: true

automation:
  - alias: Simulate a home message when blake's phone gets a dhcp lease
    trigger:
      platform: mqtt
      topic: network/dhcp/3c:28:6d:2a:f0:f4
    action:
      - service: mqtt.publish
        data_template:
          topic: location/blake_blackshear
          payload: !secret blakeshome_payload
          retain: true
      - service: device_tracker.see
        data_template:
          mac: 3C:28:6D:2A:F0:F4
          dev_id: blake_phone
          location_name: home
      - service: input_datetime.set_datetime
        entity_id: input_datetime.blake_last_seen
        data_template:
          time: '{{ trigger.payload_json.timestamp | timestamp_custom("%H:%M:%S", true) }}'
          date: '{{ trigger.payload_json.timestamp | timestamp_custom("%Y-%m-%d", true) }}'

  - alias: Filter out blake's location updates that are old and republish
    trigger:
      platform: mqtt
      topic: google/location/blake_blackshear
    condition:
      - condition: template
        value_template: '{{ trigger.payload_json.datetime > states.input_datetime.blake_last_seen.attributes.timestamp }}'
      # - condition: template
      #   value_template: '{{ trigger.payload_json.datetime > states.device_tracker.blake_phone.attributes.last_seen }}'
    action:
      - service: mqtt.publish
        data_template:
          topic: location/blake_blackshear
          payload: '{{ trigger.payload }}'
          retain: true
      - service: input_datetime.set_datetime
        entity_id: input_datetime.blake_last_seen
        data_template:
          time: '{{ trigger.payload_json.datetime | timestamp_custom("%H:%M:%S", true) }}'
          date: '{{ trigger.payload_json.datetime | timestamp_custom("%Y-%m-%d", true) }}'

  - alias: Simulate a home message when ali's phone gets a dhcp lease
    trigger:
      platform: mqtt
      topic: network/dhcp/3c:28:6d:e3:ec:c4
    action:
      - service: mqtt.publish
        data_template:
          topic: location/ali_blackshear
          payload: !secret blakeshome_payload
          retain: true
      - service: device_tracker.see
        data_template:
          mac: 3C:28:6D:E3:EC:C4
          dev_id: ali_phone
          location_name: home
      - service: input_datetime.set_datetime
        entity_id: input_datetime.ali_last_seen
        data_template:
          time: '{{ trigger.payload_json.timestamp | timestamp_custom("%H:%M:%S", true) }}'
          date: '{{ trigger.payload_json.timestamp | timestamp_custom("%Y-%m-%d", true) }}'

  - alias: Filter out ali's location updates that are old and republish
    trigger:
      platform: mqtt
      topic: google/location/ali_blackshear
    condition:
      - condition: template
        value_template: '{{ trigger.payload_json.datetime > states.input_datetime.ali_last_seen.attributes.timestamp }}'
      - condition: template
        value_template: '{{ trigger.payload_json.datetime > states.device_tracker.ali_phone.attributes.last_seen }}'
    action:
      - service: mqtt.publish
        data_template:
          topic: location/ali_blackshear
          payload: '{{ trigger.payload }}'
          retain: true
      - service: input_datetime.set_datetime
        entity_id: input_datetime.ali_last_seen
        data_template:
          time: '{{ trigger.payload_json.datetime | timestamp_custom("%H:%M:%S", true) }}'
          date: '{{ trigger.payload_json.datetime | timestamp_custom("%Y-%m-%d", true) }}'

  - alias: Notify if our location stops updating
    trigger:
      - platform: time_pattern
        minutes: '/15'
    condition:
      - condition: template
        value_template: "{{ (as_timestamp(now())-states.input_datetime.blake_last_seen.attributes.timestamp) > 3600 }}"
      - condition: template
        value_template: "{{ (as_timestamp(now())-states.input_datetime.ali_last_seen.attributes.timestamp) > 3600 }}"
    action:
      service: notify.html5_blake_phone
      data:
        message: "Uh oh. I haven't gotten a location update in over an hour."

  - alias: Update Blake last seen from Unifi
    trigger:
      - platform: state
        entity_id: sensor.blake_unifi_last_seen
    condition:
      - condition: template
        value_template: "{{ float(states('sensor.blake_unifi_last_seen')) > states.input_datetime.blake_last_seen.attributes.timestamp }}"
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.blake_last_seen
        data_template:
          time: "{{ float(states('sensor.blake_unifi_last_seen')) | timestamp_custom('%H:%M:%S', true) }}"
          date: "{{ float(states('sensor.blake_unifi_last_seen')) | timestamp_custom('%Y-%m-%d', true) }}"

  - alias: Update Ali last seen from Unifi
    trigger:
      - platform: state
        entity_id: sensor.ali_unifi_last_seen
    condition:
      - condition: template
        value_template: "{{ float(states('sensor.ali_unifi_last_seen')) > states.input_datetime.ali_last_seen.attributes.timestamp }}"
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.ali_last_seen
        data_template:
          time: "{{ float(states('sensor.ali_unifi_last_seen')) | timestamp_custom('%H:%M:%S', true) }}"
          date: "{{ float(states('sensor.ali_unifi_last_seen')) | timestamp_custom('%Y-%m-%d', true) }}"
    

