light:  
  - platform: group
    name: Foyer Lights
    entities:
      - light.foyer_front_light
      - light.foyer_back_light
  - platform: group
    name: Living Room Lights
    entities:
      - light.living_room_chandelier_light
      - light.living_room_recessed_lights

input_boolean:
  vacation_mode:
    name: Vacation Mode
    initial: off
    icon: mdi:airplane

group:
  random_away_lights:
    entities:
      - light.kitchen_lights
      - light.foyer_lights
      - light.playroom_lights
      - light.living_room_lights
      - light.master_lamps

automation:
################################################################
## Random lights on while sunset and vacation mode on
################################################################
  - alias: Random Vacation Lights
    initial_state: True
    hide_entity: False

    trigger:
      - platform: time_pattern
        minutes: '/30'
        seconds: 00

    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
    
    action:
      - delay: "00:{{ '{:02}'.format(range(1, 29) | random | int) }}:00"

      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'

      - condition: or
        conditions:
          - condition: time
            before: "01:00:00"

          - condition: sun
            after: sunset
            after_offset: "-01:00:00"

      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away

      - service: homeassistant.toggle
        data_template:
          entity_id: "{{ state_attr('group.random_away_lights','entity_id') | random }}"
  
  ##########################################################
  ## Random Lights Off
  ##########################################################
  - alias: Random Lights Off At 1AM
    initial_state: True
    hide_entity: False

    trigger:
      - platform: time
        at: "01:00:00"
    
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'

    action:
      - service: homeassistant.turn_off
        entity_id: group.random_away_lights

  ##########################################################
  ## Random lights Off
  ##########################################################
  - alias: Random Lights Off
    initial_state: True
    hide_entity: False

    trigger:
      - platform: state
        entity_id: input_boolean.vacation_mode
        from: 'on'
        to: 'off'

    action:
      - service: homeassistant.turn_off
        entity_id: group.random_away_lights
  
  - alias: Turn on vacation mode if we are both more than 50 miles away
    trigger:
      - platform: numeric_state
        entity_id: proximity.blake_home
        above: '50000'
        for:
          minutes: 15
      - platform: numeric_state
        entity_id: proximity.ali_home
        above: '50000'
        for:
          minutes: 15
    condition:
      - condition: numeric_state
        entity_id: proximity.blake_home
        above: '50000'
      - condition: numeric_state
        entity_id: proximity.ali_home
        above: '50000'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.vacation_mode
      - service: notify.blake_telegram
        data:
          message: "Vacation mode enabled."
  
  - alias: Turn off vacation mode if either of us is less than 50 miles away
    trigger:
      - platform: numeric_state
        entity_id: proximity.blake_home
        below: '50000'
        for:
          minutes: 15
      - platform: numeric_state
        entity_id: proximity.ali_home
        below: '50000'
        for:
          minutes: 15
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.vacation_mode
      - service: notify.blake_telegram
        data:
          message: "Vacation mode disabled."
    
  - alias: Set the thermostats to vacation mode
    trigger:
      - platform: state
        entity_id: input_boolean.vacation_mode
        from: 'off'
        to: 'on'
    action:
      - service: climate.set_away_mode
        data:
          away_mode: 'yes'
          entity_id:
            - climate.downstairs
            - climate.upstairs
    
  - alias: Set the thermostats to normal mode
    trigger:
      - platform: state
        entity_id: input_boolean.vacation_mode
        from: 'on'
        to: 'off'
    action:
      - service: climate.set_away_mode
        data:
          away_mode: 'no'
          entity_id:
            - climate.downstairs
            - climate.upstairs