automation:
  - alias: Run the vacuum if Ali is at the gym
    trigger:
      - platform: state
        entity_id: device_tracker.ali_phone_mqtt
        to: 'Gym'
        for:
          minutes: 10
    condition:
      condition: and
      conditions:
        - condition: time
          after: '14:30:00'
          before: '17:30:00'
          weekday:
            - tue
            - thu
        - condition: template
          value_template: "{{ not is_state('device_tracker.blake_phone_mqtt', 'home') }}"
    action:
      service: vacuum.start
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner

  - alias: Run the vacuum when Ali leaves MWF
    trigger:
      - platform: state
        entity_id: device_tracker.ali_phone_mqtt
        from: 'home'
    condition:
      - condition: time
        after: '07:30:00'
        before: '09:00:00'
        weekday:
          - mon
          - wed
          - fri
    action:
      service: vacuum.start
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner

  - alias: Ask about running the vacuum if we are gone on the weekend
    trigger:
      - platform: state
        entity_id: group.people
        to: 'not_home'
        for:
          minutes: 7
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: vacuum.xiaomi_vacuum_cleaner
          state: 'off'
        - condition: time
          weekday:
            - sat
            - sun
    action:
      service: notify.html5_blake_phone
      #target: ['specific device to notify']
      data:
        message: "Should I vacuum while you are gone?"
        data:
          actions:
            - action: 'run_vacuum'
              title: 'Yes'

  - alias: Run vacuum action clicked
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: run_vacuum
    condition:
      - condition: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        state: 'off'
    action:
      service: vacuum.start
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
