binary_sensor:
  - platform: "mqtt"
    name: Kitchen Sink Water Leak Detector
    state_topic: "zigbee/0x00158d0001d78a51"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.water_leak }}"
    device_class: "moisture"
  - platform: "mqtt"
    name: Clothes Washer Leak Detector
    state_topic: "zigbee/0x00158d00023738fc"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.water_leak }}"
    device_class: "moisture"
  - platform: "mqtt"
    name: Guest Bath Leak Detector
    state_topic: "zigbee/0x00158d0002379bac"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.water_leak }}"
    device_class: "moisture"
  - platform: "mqtt"
    name: Main HVAC Pan Water Detector
    state_topic: "zigbee/0x00158d000237390f"
    availability_topic: "zigbee/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.water_leak }}"
    device_class: "moisture"

automation:
  - alias: Send a text message if a water leak is detected
    trigger:
      - platform: state
        entity_id: group.water_leak_detectors 
        from: 'off'
        to: 'on'
        for:
          minutes: 1
    action:
      - service: notify.blakeshome_sms
        data_template:
          message: 'A water leak was detected!'
          target:
            - !secret blake_phone_number