scene:
  - name: Daytime Away
    entities:
      light.over_cabinet: off
      light.under_cabinet: off
      light.kitchen_lights: off
      light.butlers_pantry_light: off
      light.pantry_light: off
      light.foyer_back_light: off
      light.foyer_front_light: off
      light.half_bath_bathroom_light: off
      light.half_bath_hall_light: off
      light.playroom_light: off
      light.dining_room_light: off
      light.living_room_chandelier_light: off
      light.living_room_recessed_lights: off
      remote.living_room: off
      media_player.living_room: off
      media_player.living_room_2: off
      media_player.living_room_and_deck: off
      light.master_bath_lights: off
      light.master_closet_lights: off
      light.master_shower_light: off
      light.hall_lights: off
      light.hall_stairs_light: off
      light.laundry_room_light: off
      light.driveway_lights: off
      light.deck_recessed_lights: off
      light.deck_string_lights: off
      light.media_stairs_light: off
  - name: Daytime Arrived
    entities:
      light.over_cabinet:
        state: on
        brightness: 130
      light.under_cabinet:
        state: on
        brightness: 130
      light.kitchen_island_lights:
        state: on
        brightness: 130
      light.kitchen_breakfast_lights:
        state: on
        brightness: 100
      light.kitchen_recessed_lights:
        state: on
        brightness: 130
      light.foyer_front_light:
        state: on
        brightness: 90
      light.foyer_back_light:
        state: on
        brightness: 90
  - name: Nighttime Away
    entities:
      light.over_cabinet: off
      light.under_cabinet: off
      light.kitchen_lights: off
      light.butlers_pantry_light: off
      light.pantry_light: off
      light.foyer_back_light: off
      light.foyer_front_light: 
        state: on
        brightness: 90
      light.half_bath_bathroom_light: off
      light.half_bath_hall_light: off
      light.playroom_light: off
      light.dining_room_light: off
      light.living_room_chandelier_light: off
      light.living_room_recessed_lights: off
      remote.living_room: off
      media_player.living_room: off
      media_player.living_room_2: off
      media_player.living_room_and_deck: off
      light.master_bath_lights: off
      light.master_closet_lights: off
      light.master_shower_light: off
      light.hall_lights: off
      light.hall_stairs_light: off
      light.laundry_room_light: off
      light.driveway_lights: off
      light.deck_recessed_lights: off
      light.deck_string_lights: off
      light.media_stairs_light: off
  - name: Goodnight
    entities:
      light.kitchen_lights: off
      light.butlers_pantry_light: off
      light.pantry_light: off
      light.foyer_back_light: off
      light.foyer_front_light: 
        state: on
        brightness: 90
      light.half_bath_bathroom_light: off
      light.half_bath_hall_light: off
      light.playroom_light: off
      light.dining_room_light: off
      light.living_room_chandelier_light: off
      light.living_room_recessed_lights: off
      remote.living_room: off
      media_player.living_room: off
      media_player.living_room_2: off
      media_player.living_room_and_deck: off
      light.hall_stairs_light: off
      light.laundry_room_light: off
      switch.fireplace: off
  - name: Nighttime Arrived
    entities:
      light.over_cabinet:
        state: on
        brightness: 130
      light.under_cabinet:
        state: on
        brightness: 75
      light.kitchen_lights:
        state: on
        brightness: 90
      light.foyer_front_light:
        state: on
        brightness: 90
      light.foyer_back_light:
        state: on
        brightness: 90


automation:
  - alias: Activate scene when we arrive during the day
    trigger:
      - platform: state
        entity_id: group.people
        to: 'home'
    condition:
      - condition: time
        before: '22:00:00'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: scene.turn_on
        data_template:
          entity_id: scene.daytime_arrived
  - alias: Activate scene when we arrive at night
    trigger:
      - platform: state
        entity_id: group.people
        to: 'home'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: sun
            before: sunrise
          - condition: time
            after: '22:00:00'
    action:
      - service: scene.turn_on
        data_template:
          entity_id: scene.nighttime_arrived
  - alias: Activate scene when we are away during the day
    trigger:
      - platform: state
        entity_id: group.people
        to: 'not_home'
      - platform: sun
        event: sunrise
    condition:
      - condition: time
        before: '22:00:00'
      - condition: state
        entity_id: group.people
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: scene.turn_on
        data_template:
          entity_id: scene.daytime_away
  - alias: Activate night away scene
    trigger:
      - platform: sun
        event: sunset
      - platform: state
        entity_id: group.people
        to: 'not_home'
    condition:
      - condition: or
        conditions:
          - condition: sun
            before: sunrise
          - condition: time
            after: '22:00:00'
      - condition: state
        entity_id: group.people
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: scene.turn_on
        data_template:
          entity_id: scene.nighttime_away